apiVersion: v1
kind: Pod
metadata:
  name: kafka-rest
  labels:
    app: kafka-rest
    version: v1
spec:
  containers:
  - name: kafka-rest
    image: confluentinc/cp-kafka-rest:3.1.1
    ports:
    - containerPort: 8082
      protocol: TCP
    env:
    - name: KAFKA_REST_ZOOKEEPER_CONNECT
      value: kafka01:2181,kafka02:2181,kafka03:2181
    - name: KAFKA_REST_HOST_NAME
      value: kafka04.teambition.corp
    - name: KAFKA_REST_LISTENERS
      value: http://0.0.0.0:8082
    - name: KAFKA_REST_SCHEMA_REGISTRY_URL
      value: http://kafka04:8081
