apiVersion: v1
kind: Pod
metadata:
  name: kafka-rest
  labels:
    app: kafka-rest
    version: v1
spec:
  containers:
  - name: kafka-rest
    image: confluentinc/cp-kafka-rest:3.1.1
    ports:
    - containerPort: 8082
      protocol: TCP
    env:
    - name: KAFKA_REST_ZOOKEEPER_CONNECT
      value: 10.0.0.1:22181,10.0.0.1:32181,10.0.0.1:42181
    - name: KAFKA_REST_HOST_NAME
      value: 121.196.214.67
    - name: KAFKA_REST_LISTENERS
      value: http://0.0.0.0:8082
    - name: KAFKA_REST_SCHEMA_REGISTRY_URL
      value: http://10.0.0.1:38081
